In [1]:
import numpy as np

**Note:** Most of  the libraries in Data Science such as Pandas, Matplotlib, Seaborn, Scikit-learn, etc. are built on top of NumPy. Therefore, having a good understanding of NumPy is essential for anyone looking to excel in Data Science and Machine Learning.
- Section Goals: 
    - Understand Numpy
    - Learn how to create Numpy arrays
    - Retrieve and manipulate data in Numpy arrays
    - Learn basic numpy operations
    - Test Numpy skills with exercises questions

- What is NumPy?
    - NumPy, which stands for Numerical Python, is an open-source library in Python that provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.
    - It is widely used in data science, machine learning, scientific computing, and engineering due to its powerful capabilities for numerical computations.

## 1. Creating Numpy Arrays

In [4]:
mylist = [1,2,3]
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
mylist

[1, 2, 3]

In [7]:
myarr = np.array(mylist)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.eye(10) @ np.arange(30).reshape(10,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]])

In [31]:
np.arange(30).reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [47]:
np.random.rand(5, 6)

array([[0.36645122, 0.95039655, 0.73349791, 0.31087772, 0.74023879,
        0.2761193 ],
       [0.89506792, 0.82656773, 0.12170402, 0.24141983, 0.77705001,
        0.45055822],
       [0.59001917, 0.0939775 , 0.13001813, 0.62338489, 0.7873565 ,
        0.32957078],
       [0.75820772, 0.23689186, 0.36226235, 0.25206543, 0.18119452,
        0.66267675],
       [0.76565867, 0.32664042, 0.32425538, 0.97299295, 0.40679768,
        0.71475485]])

In [48]:
np.random.randn(10)

array([ 0.2892278 , -0.52571821, -0.47878714,  2.63579003, -0.97820425,
       -0.17678227, -1.37592808,  0.92810408, -2.10271619,  1.02042463])

In [49]:
np.random.randn(2,3)

array([[ 0.91778691,  0.61704116, -0.5736673 ],
       [ 0.64740616,  2.60570883, -0.6479144 ]])

In [51]:
np.random.randn(2,3,3, 4)

array([[[[-0.15684403,  1.27876437,  1.25334025, -0.90220945],
         [ 0.20967902,  0.80171972, -0.49257833,  0.00359815],
         [-1.44715873,  0.25831925,  1.3960499 , -1.09088716]],

        [[ 1.69252259,  0.53303503,  0.36185482, -0.95922082],
         [-0.46812905, -0.75217146,  0.49498719, -0.40321996],
         [-0.2192255 , -1.01133915,  0.07831299, -1.18756816]],

        [[ 0.26044034,  3.13671209,  1.12961272,  0.21122674],
         [ 1.70879997, -0.9883847 , -0.40501141,  1.41370964],
         [ 0.99733945,  0.82217947,  2.19583842,  0.48265609]]],


       [[[-0.53940883,  2.14916626,  1.69171107,  0.39898578],
         [-1.24514508,  1.30136585,  0.20634996,  1.08377357],
         [ 2.08113742, -0.59193771, -0.81171593,  0.20599408]],

        [[ 1.7895319 ,  2.04384958,  0.4466732 ,  0.03599328],
         [ 0.9120685 ,  0.68887454,  0.21066535, -0.55516472],
         [-0.52569367,  0.44298996, -0.00613951,  1.53025065]],

        [[-0.87026312, -1.49311317,  2.0555

In [ ]:
np.random.randint(0, 10, (3, 5)) 

array([[8, 0, 6, 7, 3],
       [9, 0, 2, 0, 1],
       [9, 2, 6, 3, 1]])

In [58]:
np.random.seed(42)
np.random.randn(4)


array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [59]:
rng = np.random.default_rng(42) # Seed in here to use it multiple times
rng.random(3)

array([0.77395605, 0.43887844, 0.85859792])

In [63]:
print(rng.random(4))
rng.random(4)

[0.6316644  0.75808774 0.35452597 0.97069802]


array([0.89312112, 0.7783835 , 0.19463871, 0.466721  ])

In [61]:
rng.random(4)

array([0.78606431, 0.12811363, 0.45038594, 0.37079802])

In [64]:
arr = np.arange(0, 25)

In [65]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
ranarr = np.random.randint(0,101,10)

In [68]:
ranarr.max()

np.int64(99)

In [69]:
ranarr.min()

np.int64(2)

In [70]:
ranarr.argmax()

np.int64(5)

In [71]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [73]:
ranarr.argmin()

np.int64(7)

In [75]:
ranarr.dtype = "int32"

In [76]:
ranarr.dtype

dtype('int32')

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
arr.shape

(25,)

In [79]:
arr = arr.reshape((5,5))

In [80]:
arr.shape

(5, 5)

In [81]:
myarray = np.linspace(0,10,101)

In [82]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

## 2 - Indexing and Selection in NumPy

In [83]:
arr = np.arange(0,11)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr[8]

np.int64(8)

In [86]:
arr[1:5]

array([1, 2, 3, 4])

In [87]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [88]:
arr[:5]

array([0, 1, 2, 3, 4])

In [89]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**BroadCasting in NumPy:**

In [91]:
arr[0:5] = 100

In [92]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [93]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[0:5] # This will point to the same address anything we do in slice_of_arr also change our original array: call by reference

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [97]:
slice_of_arr[:] = 99

In [98]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [99]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [100]:
# To prevent this
slice_of_arr2 = arr[0:5].copy()

In [101]:
slice_of_arr2[:] = 11

In [102]:
slice_of_arr2

array([11, 11, 11, 11, 11])

In [ ]:
arr # arr doesnt change because slice_of_arr2 is call by value variable

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [104]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

In [105]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d.shape = (9,) # we can change the property of it

In [107]:
arr_2d

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [108]:
arr_2d[0]

np.int64(5)

In [109]:
arr_2d.shape = 3,3

In [110]:
arr_2d[1][1]

np.int64(25)

In [111]:
arr_2d[0, 2]

np.int64(15)

In [114]:
arr_2d[:2, 1:3]

array([[10, 15],
       [25, 30]])

In [115]:
arr = np.arange(1,11)

In [118]:
myList = list(arr > 4)

In [120]:
arr[myList]

array([ 5,  6,  7,  8,  9, 10])

In [121]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])


In [123]:
len(dice_rolls[dice_rolls > 2])

19

## 3 - Basic Operations in NumPy

In [124]:
arr = np.arange(0,10)

In [125]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [127]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
arr + arr # of course they need to be same shape

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [129]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [130]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [131]:
arr / arr

/var/folders/xc/rfws523562j79_1wnw1hgt_c0000gn/T/ipykernel_37448/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1 / arr # returns infinity

/var/folders/xc/rfws523562j79_1wnw1hgt_c0000gn/T/ipykernel_37448/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [134]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [135]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [136]:
np.log(arr)

/var/folders/xc/rfws523562j79_1wnw1hgt_c0000gn/T/ipykernel_37448/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [139]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
arr.sum()

np.int64(45)

In [141]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
arr.var() #variance

np.float64(8.25)

In [143]:
arr.std()

np.float64(2.8722813232690143)

In [144]:
arr.mean()

np.float64(4.5)

In [147]:
arr2d = np.arange(0, 25).reshape((5,5))

In [148]:
arr2d.sum()

np.int64(300)

In [ ]:
arr2d.sum(axis=0) # columns

array([50, 55, 60, 65, 70])

In [153]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

## 4 - Exercises

In [154]:
arr = np.zeros(10)

In [155]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [156]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [157]:
arr[:] = 10

In [159]:
np.ones(10) + 4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [160]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [161]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [162]:
np.random.randint(0, 9, (3,3))

array([[1, 7, 5],
       [1, 4, 0],
       [5, 8, 0]])

In [164]:
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [165]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [166]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [170]:
np.random.rand(2,3, 4)

array([[[0.98323089, 0.46676289, 0.85994041, 0.68030754],
        [0.45049925, 0.01326496, 0.94220176, 0.56328822],
        [0.3854165 , 0.01596625, 0.23089383, 0.24102547]],

       [[0.68326352, 0.60999666, 0.83319491, 0.17336465],
        [0.39106061, 0.18223609, 0.75536141, 0.42515587],
        [0.20794166, 0.56770033, 0.03131329, 0.84228477]]])

In [174]:
np.linspace(0.01, 1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [175]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [176]:
mat = np.arange(1, 26).reshape(5,5)

In [177]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [180]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [182]:
mat[3, 4]

np.int64(20)

In [184]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [185]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [186]:
mat[4]

array([21, 22, 23, 24, 25])

In [187]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [188]:
mat.sum()

np.int64(325)

In [189]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [191]:
float(mat.std())

7.211102550927978

In [192]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [194]:
rng = np.random.default_rng(42)
rng.random(1)

array([0.77395605])

In [196]:
rng.random(1)

array([0.85859792])